version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Running tests
          command: npm test
      - run:
          name: Collect coverage
          command: npm run coverage
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  version: 2
  npm-publish:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
