version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Running tests
          command: npm run test
      - store_artifacts:
          path: coverage
      - run:
          name: Build
          command: npm run build
