version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Running tests
          command: npm test
      - run:
          name: Collect coverage
          command: npm run coverage
      - run:
          name: Build
          command: npm run build
  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  npm-publish:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
